require('dotenv').config();

module.exports = {
  env: {
    REACT_APP_MEAL_SERVICE_KEY: process.env.REACT_APP_MEAL_SERVICE_KEY,
    REACT_APP_FIREBASE_SERVICE_API_KEY: process.env.REACT_APP_FIREBASE_SERVICE_API_KEY,
    REACT_APP_FIREBASE_SERVICE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_SERVICE_AUTH_DOMAIN,
    REACT_APP_FIREBASE_SERVICE_DATABASE_URL: process.env.REACT_APP_FIREBASE_SERVICE_DATABASE_URL,
    REACT_APP_FIREBASE_SERVICE_PROJECT_ID: process.env.REACT_APP_FIREBASE_SERVICE_PROJECT_ID,
    REACT_APP_FIREBASE_SERVICE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_SERVICE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_SERVICE_MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_SERVICE_MESSAGING_SENDER_ID,
    REACT_APP_FIREBASE_SERVICE_APP_ID: process.env.REACT_APP_FIREBASE_SERVICE_APP_ID,
  },
}